import { Link } from "react-router-dom"

export const PrivacyPolicy = () => {
     var acc = document.getElementsByClassName("policies__header");
     var i;

     let AccordionState = () => {
          for (i = 0; i < acc.length; i++) {
               acc[i].addEventListener("click", function () {
                    this.classList.toggle("active");
                    var panel = this.nextElementSibling;
                    if (panel.style.maxHeight) {
                         panel.style.maxHeight = null;
                    } else {
                         panel.style.maxHeight = panel.scrollHeight + "px";
                    }
               });
          }
     }

     return (
          <>
               <section className="policies">
                    <h2 className="policies__header" onClick={AccordionState}>
                         Notice of Privacy Practices
                    </h2>
                    <div className="policies__body">
                         <div className="policies__emphasis">THIS NOTICE DESCRIBES HOW HEALTH INFORMATION MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY.</div>
                         <div className="policies__paragraph">
                              I understand that health information about you and your health care is personal. I am committed to protecting health information about you. I create a record of the care and services you receive from me. I need this record to provide you with quality care and to comply with certain legal requirements. This notice applies to all of the records of your care generated by this mental health care practice. This notice will tell you about the ways in which I may use and disclose health information about you. I also describe your rights to the health information I keep about you, and describe certain obligations I have regarding the use and disclosure of your health information. I am required by law to:
                         </div>
                         <ul className="privacy-policy__list">
                              <li className="privacy-policy__list-item">
                                   Make sure that protected health information (“PHI”) that identifies you is kept private.
                              </li>
                              <li className="privacy-policy__list-item">
                                   Give you this notice of my legal duties and privacy practices with respect to health information.
                              </li>
                              <li className="privacy-policy__list-item">
                                   Follow the terms of the notice that is currently in effect.
                              </li>
                              <li className="privacy-policy__list-item">
                                   I can change the terms of this Notice, and such changes will apply to all information I have about you. The new Notice will be available upon request, in my office, and on my website.
                              </li>
                         </ul>
                         <div className="privacy-policy__body">
                              The following categories describe different ways that I use and disclose health information. For each category of uses or disclosures I will explain what I mean and try to give some examples. Not every use or disclosure in a category will be listed. However, all of the ways I am permitted to use and disclose information will fall within one of the categories.
                         </div>
                         <ul className="privacy-policy__list">
                              <li className="privacy-policy__list-item">
                                   <span className="policies__emphasis-underline">Lawsuits and Disputes</span>: If you are involved in a lawsuit, I may disclose health information in response to a court or administrative order. I may also disclose health information about your child in response to a subpoena, discovery request, or other lawful process by someone else involved in the dispute, but only if efforts have been made to tell you about the request or to obtain an order protecting the information requested.
                              </li>
                              <li className="privacy-policy__list-item">
                                   <span className="policies__emphasis-underline">For Treatment Payment, or Health Care Operations</span>: Federal privacy rules (regulations) allow health care providers who have direct treatment relationship with the patient/client to use or disclose the patient/client’s personal health information without the patient’s written authorization, to carry out the health care provider’s own treatment, payment or health care operations. I may also disclose your protected health information for the treatment activities of any health care provider. This too can be done without your written authorization. For example, if a clinician were to consult with another licensed health care provider about your condition, we would be permitted to use and disclose your personal health information, which is otherwise confidential, in order to assist the clinician in diagnosis and treatment of your mental health condition.
                              </li>
                              <li className="privacy-policy__list-item">
                                   Disclosures for treatment purposes are not limited to the minimum necessary standard. Because therapists and other health care providers need access to the full record and/or full and complete information in order to provide quality care. The word “treatment” includes, among other things, the coordination and management of health care providers with a third party, consultations between health care providers and referrals of a patient for health care from one health care provider to another.
                              </li>
                         </ul>
                         <div className="privacy-policy__body">
                              As a psychotherapist, I will not use or disclose your PHI for marketing purposes or sell your PHI in the regular course of my business. I do keep “psychotherapy notes” as that term is defined in 45 CFR § 164.501, and any use or disclosure of such notes requires your Authorization unless the use or disclosure is:
                         </div>
                         <ol className="privacy-policy__list">
                              <li className="privacy-policy__list-item">
                                   For my use in treating you.
                              </li>
                              <li className="privacy-policy__list-item">
                                   For my use in training or supervising mental health practitioners to help them improve their skills in group, joint, family, or individual counseling or therapy.
                              </li>
                              <li className="privacy-policy__list-item">
                                   For my use in defending myself in legal proceedings instituted by you.
                              </li>
                              <li className="privacy-policy__list-item">
                                   For use by the Secretary of Health and Human Services to investigate my compliance with HIPAA.
                              </li>
                              <li className="privacy-policy__list-item">
                                   Required by law and the use or disclosure is limited to the requirements of such law.
                              </li>
                              <li className="privacy-policy__list-item">
                                   Required by law for certain health oversight activities pertaining to the originator of the psychotherapy notes.
                              </li>
                              <li className="privacy-policy__list-item">
                                   Required by a coroner who is performing duties authorized by law.
                              </li>
                              <li className="privacy-policy__list-item">
                                   Required to help avert a serious threat to the health and safety of others.
                              </li>
                         </ol>
                         <div className="privacy-policy__body">
                              Subject to certain limitations in the law, I can use and disclose your PHI without your Authorization for the following reasons:
                         </div>
                         <ol className="privacy-policy__list">
                              <li className="privacy-policy__list-item">
                                   When disclosure is required by state or federal law, and the use or disclosure complies with and is limited to the relevant requirements of such law.
                              </li>
                              <li className="privacy-policy__list-item">
                                   For public health activities, including reporting suspected child, elder, or dependent adult abuse, or preventing or reducing a serious threat to anyone’s health or safety.
                              </li>
                              <li className="privacy-policy__list-item">
                                   For health oversight activities, including audits and investigations.
                              </li>
                              <li className="privacy-policy__list-item">
                                   For judicial and administrative proceedings, including responding to a court or administrative order, although my preference is to obtain an Authorization from you before doing so.
                              </li>
                              <li className="privacy-policy__list-item">
                                   For law enforcement purposes, including reporting crimes occurring on my premises.
                              </li>
                              <li className="privacy-policy__list-item">
                                   To coroners or medical examiners, when such individuals are performing duties authorized by law.
                              </li>
                              <li className="privacy-policy__list-item">
                                   For research purposes, including studying and comparing the mental health of patients who received one form of therapy versus those who received another form of therapy for the same condition.
                              </li>
                              <li className="privacy-policy__list-item">
                                   Specialized government functions, including, ensuring the proper execution of military missions; protecting the President of the United States; conducting intelligence or counter-intelligence operations; or, helping to ensure the safety of those working within or housed in correctional institutions.
                              </li>
                              <li className="privacy-policy__list-item">
                                   For workers’ compensation purposes. Although my preference is to obtain an Authorization from you, I may provide your PHI in order to comply with workers’ compensation laws.
                              </li>
                              <li className="privacy-policy__list-item">
                                   Appointment reminders and health related benefits or services. I may use and disclose your PHI to contact you to remind you that you have an appointment with me. I may also use and disclose your PHI to tell you about treatment alternatives, or other health care services or benefits that I offer.
                              </li>
                         </ol>
                         <div className="privacy-policy__body">
                              Certain uses and disclosures require you to have the opportunity to object, such as disclosures to family, friends, or others. I may provide your PHI to a family member, friend, or other person that you indicate is involved in your care or the payment for your health care, unless you object in whole or in part. The opportunity to consent may be obtained retroactively in emergency situations.
                         </div>
                         <div className="privacy-policy__emphasis">
                              YOU HAVE THE FOLLOWING RIGHTS WITH RESPECT TO YOUR PHI:
                         </div>
                         <ul className="privacy-policy__list">
                              <li className="privacy-policy__list-item">
                                   The Right to Request Limits on Uses and Disclosures of Your PHI. You have the right to ask me not to use or disclose certain PHI for treatment, payment, or health care operations purposes. I am not required to agree to your request, and I may say “no” if I believe it would affect your health care.
                              </li>
                              <li className="privacy-policy__list-item">
                                   The Right to Request Restrictions for Out-of-Pocket Expenses Paid for In Full. You have the right to request restrictions on disclosures of your PHI to health plans for payment or health care operations purposes if the PHI pertains solely to a health care item or a health care service that you have paid for out-of-pocket in full.
                              </li>
                              <li className="privacy-policy__list-item">
                                   The Right to Choose How I Send PHI to You. You have the right to ask me to contact you in a specific way (for example, home or office phone) or to send mail to a different address, and I will agree to all reasonable requests.
                              </li>
                              <li className="privacy-policy__list-item">
                                   The Right to See and Get Copies of Your PHI. Other than “psychotherapy notes,” you have the right to get an electronic or paper copy of your medical record and other information that I have about you. I will provide you with a copy of your record, or a summary of it, if you agree to receive a summary, within 30 days of receiving your written request, and I may charge a reasonable, cost based fee for doing so.
                              </li>
                              <li className="privacy-policy__list-item">
                                   The Right to Get a List of the Disclosures I Have Made.You have the right to request a list of instances in which I have disclosed your PHI for purposes other than treatment, payment, or health care operations, or for which you provided me with an Authorization. I will respond to your request for an accounting of disclosures within 60 days of receiving your request. The list I will give you will include disclosures made in the last six years unless you request a shorter time. I will provide the list to you at no charge, but if you make more than one request in the same year, I will charge you a reasonable cost based fee for each additional request.
                              </li>
                              <li className="privacy-policy__list-item">
                                   The Right to Correct or Update Your PHI. If you believe that there is a mistake in your PHI, or that a piece of important information is missing from your PHI, you have the right to request that I correct the existing information or add the missing information. I may say “no” to your request, but I will tell you why in writing within 60 days of receiving your request.
                              </li>
                              <li className="privacy-policy__list-item">
                                   The Right to Get a Paper or Electronic Copy of this Notice. You have the right to a paper copy of this Notice, and you have the right to get a copy of this notice by email. And, even if you have agreed to receive this Notice via email, you also have the right to request a paper copy of it.
                              </li>
                         </ul>
                         <div className="privacy-policy__body">
                              The effective date of this Notice is August 2023.
                         </div>
                         <div>
                              <Link className="privacy-policy__link" to={"https://support.simplepractice.com/hc/en-us/articles/10791430516365-Using-consent-documents-and-intake-forms"} target="_blank">
                                   https://support.simplepractice.com/hc/en-us/articles/10791430516365-Using-consent-documents-and-intake-forms
                              </Link>
                         </div>
                    </div>
               </section>
          </>
     )
}